# Generated by Django 5.2.6 on 2025-09-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('contacts', models.CharField(max_length=100, unique=True, verbose_name='Контактные данные')),
                ('passport_number', models.CharField(max_length=30, verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название блюда')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Event_statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус события',
                'verbose_name_plural': 'Статусы событий',
            },
        ),
        migrations.CreateModel(
            name='Event_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
            },
        ),
        migrations.CreateModel(
            name='Hotel_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Имя организатора')),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название должности')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Оклад')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Room_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_class', models.CharField(max_length=20, unique=True, verbose_name='Класс комнаты')),
                ('number_of_beds', models.IntegerField(verbose_name='Количество мест')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Класс номера',
                'verbose_name_plural': 'Классы номера',
            },
        ),
        migrations.CreateModel(
            name='Room_statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_status', models.CharField(max_length=30, unique=True, verbose_name='Статус комнаты')),
            ],
            options={
                'verbose_name': 'Статус номера',
                'verbose_name_plural': 'Статусы номера',
            },
        ),
        migrations.CreateModel(
            name='Service_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название события')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_date', models.DateField(verbose_name='Дата завершения')),
                ('end_time', models.TimeField(verbose_name='Время завершения')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Общая цена')),
                ('event_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.event_statuses', verbose_name='id Статуса события')),
                ('event_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.event_types', verbose_name='id Типа события')),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.organizers', verbose_name='id Организаторов')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Clients_at_the_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.clients', verbose_name='id Клиента')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.events', verbose_name='id Событий')),
            ],
            options={
                'verbose_name': 'Клиент на событии',
                'verbose_name_plural': 'Клиенты на событиях',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='hotel_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.hotel_rooms', verbose_name='id Комнат'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('passport', models.CharField(max_length=40, verbose_name='Паспротные данные')),
                ('contacts', models.CharField(max_length=40, verbose_name='Контактные данные')),
                ('hiring_date', models.DateField(verbose_name='Дата приема на работу')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.posts', verbose_name='id Должностей')),
                ('sex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.sex', verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Room_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.clients', verbose_name='id Клиента')),
                ('hotel_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.hotel_rooms', verbose_name='id Номера')),
            ],
        ),
        migrations.AddField(
            model_name='hotel_rooms',
            name='class_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.room_classes', verbose_name='id Класса номера'),
        ),
        migrations.CreateModel(
            name='Room_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.dishes', verbose_name='id Блюда')),
                ('hotel_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.hotel_rooms', verbose_name='id Номера')),
            ],
        ),
        migrations.AddField(
            model_name='hotel_rooms',
            name='room_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.room_statuses', verbose_name='id Статуса номера'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Null', max_length=30, unique=True, verbose_name='Название услуги')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Стоимость услуги')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.service_types', verbose_name='id Типа услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Provision_of_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.clients', verbose_name='id Клиента')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.employee', verbose_name='id Работника')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.services', verbose_name='id Услуги')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='sex_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_app.sex', verbose_name='Пол'),
        ),
    ]
