from django.contrib import admin
from .models import *

# admin.site.register(Author)
# admin.site.register(Book)
# admin.site.register(Publisher)

admin.site.register(Clients)
admin.site.register(Clients_at_the_event)
admin.site.register(Dishes)
admin.site.register(Employee)
admin.site.register(Event_statuses)
admin.site.register(Event_types)
admin.site.register(Events)
admin.site.register(Hotel_rooms)
admin.site.register(Organizers)
admin.site.register(Posts)
admin.site.register(Provision_of_service)
admin.site.register(Room_booking)
admin.site.register(Room_classes)
admin.site.register(Room_service)
admin.site.register(Room_statuses)
admin.site.register(Service_types)
admin.site.register(Services)
admin.site.register(Sex)
